# Generated by Django 2.1.7 on 2020-12-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='')),
                ('author', models.CharField(default='anonimous', max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('describe', models.TextField(default='no description')),
            ],
        ),
    ]
